### PR TITLE
Updated EGEDA data

### PR DESCRIPTION
**Pull request by wogandavid**
The previous EGEDA data was not actually in 'tidy' format! I modified the script so to correct that. I also added in a conversion for ktoe to PJ. Values in both units are written to the csv file.

The demand model notebooks will need to be modified slightly to use the updated EGEDA data. I made the modifications in the Agriculture Demand notebook. 

Demand modelers, please test the notebooks.

To test:
1. Run the EGEDA notebook.
2. Run the Agriculture notebook to check that it works. 

Once everyone is comfortable with the changes we can merge them in to the master branch.

**Note: you will need to run the EGEDA notebook to make the new data file because it is too big to commit.**

### CODE REVIEW

**Comment by Hugh-Tate** [comment]
This update works for me. My only comment is should we be removing the non-functunal bits of test code from master branch code? eg are the .head() .info .tail etc. needed?

**Comment by wogandavid** [comment]
> This update works for me. My only comment is should we be removing the non-functunal bits of test code from master branch code? eg are the .head() .info .tail etc. needed?

@Hugh-Tate hugh I don't have a strong feeling. I think at this stage the code is for ourselves and so having the .head() and .tail() is helpful for understanding what is going on.

I have a strong feeling about committing the outputs, though.

**Comment by mathewhorne** [comment]
> 
> 
> It works!
> a minor comment, please activate code in line 38 to replace abbreviation for Canada from 03_CAN to 03_CDA.

If something's not working as intended, then feel free to amend and re-run as you see fit.

i.e. if you open it, run it, and it works, that's great. But if something isn't working or whatever, you can make changes, and then commit once you're happy with the updated version.

**Comment by wogandavid** [comment]
> Changed conversion factor
> 41.868 converts toe to PJ
> But the EGEDA data is Ktoe so the conversion factor should be 0.041868
> Would appreciate second opinion @wogandavid?
> A few other changes, including removing 20_USA from dictionary as it's already the same ('20_USA': '20_USA') . Was there a reason why '20_USA' needs to be changed? Couldn't find the approved abbreviation list.
> Also threw in underscores to column names. This might be annoying for code that then uses the subsequent EGEDA data

Good catch!!

I'm using the 0.041868 conversion as noticed by @mathewhorne . I checked the raw EGEDA file and the US is shown as 20_USA so don't need to change that name.

I committed the notebook (after clearing the outputs!).

I'll update the example demand notebook with code to read in the new format.

**Pull request merged**
